### ISSUE TITLE
base < 4.8 Restriction Breaks Build

### ISSUE THREAD

**Issue by theNerd247** [evolutics/haskell-formatter#10]
When performing a clean clone and build using `make sandbox`: 

```
cabal sandbox init
Writing a default package environment file to
/home/noah/src/com/haskell-formatter/cabal.sandbox.config
Using an existing sandbox located at
/home/noah/src/com/haskell-formatter/.cabal-sandbox
make build
make[1]: Entering directory '/home/noah/src/com/haskell-formatter'
cabal install --only-dependencies --enable-tests -j
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: haskell-formatter-1.0.0 (user goal)
next goal: base (dependency of haskell-formatter-1.0.0)
rejecting: base-4.8.2.0/installed-0d6... (conflict: haskell-formatter =>
base>=4.6 && <4.8)
rejecting: base-4.9.0.0, 4.8.2.0, 4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0,
4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0,
4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global
constraint requires installed instance)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
make[1]: *** [Makefile:10: build] Error 1
make[1]: Leaving directory '/home/noah/src/com/haskell-formatter'
make: *** [Makefile:33: sandbox] Error 2
```

**Comment by theNerd247** [comment]
Compiling succeeds with removing the restrictions however running tests fail with [this][1]

[1]: cabal install --only-dependencies --enable-tests -j
Resolving dependencies...
All the requested packages are already installed:
Use --reinstall if you want to reinstall anyway.
cabal configure --enable-tests
Resolving dependencies...
Configuring haskell-formatter-1.0.0...
cabal build -j
Building haskell-formatter-1.0.0...
Preprocessing library haskell-formatter-1.0.0...
In-place registering haskell-formatter-1.0.0...
Preprocessing executable 'haskell-formatter' for haskell-formatter-1.0.0...
Preprocessing test suite 'test' for haskell-formatter-1.0.0...
cabal test -j
Preprocessing library haskell-formatter-1.0.0...
In-place registering haskell-formatter-1.0.0...
Preprocessing test suite 'test' for haskell-formatter-1.0.0...
Running 1 test suites...
Test suite test: RUNNING...
Root
  Source code standard
    src/library/Language/Haskell/Formatter/CommentCore.hs:              OK (0.09s)
    src/library/Language/Haskell/Formatter/Configuration.hs:            OK (0.03s)
    src/library/Language/Haskell/Formatter/Error.hs:                    OK (0.03s)
    src/library/Language/Haskell/Formatter/ExactCode.hs:                OK (0.03s)
    src/library/Language/Haskell/Formatter/Internal/MapTree.hs:         OK (0.03s)
    src/library/Language/Haskell/Formatter/Internal/Newline.hs:         OK (0.02s)
    src/library/Language/Haskell/Formatter/Internal/StyleFileFormat.hs: OK (0.04s)
    src/library/Language/Haskell/Formatter/Internal/TreeFormat.hs:      OK (0.04s)
    src/library/Language/Haskell/Formatter/Location.hs:                 OK (0.01s)
    src/library/Language/Haskell/Formatter/Main.hs:                     OK (0.03s)
    src/library/Language/Haskell/Formatter/Process/AttachComments.hs:   OK (0.05s)
    src/library/Language/Haskell/Formatter/Process/Code.hs:             OK (0.03s)
    src/library/Language/Haskell/Formatter/Process/CodeOrdering.hs:     OK (0.03s)
    src/library/Language/Haskell/Formatter/Process/Control.hs:          OK (0.02s)
    src/library/Language/Haskell/Formatter/Process/DetachComments.hs:   OK (0.02s)
    src/library/Language/Haskell/Formatter/Process/FormatActualCode.hs: OK (0.04s)
    src/library/Language/Haskell/Formatter/Process/FormatComments.hs:   OK (0.01s)
    src/library/Language/Haskell/Formatter/Process/Formatter.hs:        OK (0.04s)
    src/library/Language/Haskell/Formatter/Process/LineTool.hs:         OK (0.03s)
    src/library/Language/Haskell/Formatter/Process/Note.hs:             OK (0.02s)
    src/library/Language/Haskell/Formatter/Result.hs:                   OK (0.02s)
    src/library/Language/Haskell/Formatter/Source.hs:                   OK (0.03s)
    src/library/Language/Haskell/Formatter/Style.hs:                    OK (0.03s)
    src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:         OK (0.04s)
    src/library/Language/Haskell/Formatter/Toolkit/Splitter.hs:         OK (0.04s)
    src/library/Language/Haskell/Formatter/Toolkit/StreamName.hs:       OK (0.01s)
    src/library/Language/Haskell/Formatter/Toolkit/Visit.hs:            OK (0.04s)
    src/library/Language/Haskell/Formatter.hs:                          OK (0.02s)
    src/executable/Main.hs:                                             OK (0.04s)
    testsuite/src/Language/Haskell/Formatter/Internal/Tests.hs:         OK (0.02s)
    testsuite/src/Language/Haskell/Formatter/Tests.hs:                  OK (0.04s)
    testsuite/src/Language/Haskell/Formatter/Toolkit/FileTesting.hs:    OK (0.03s)
    testsuite/src/Language/Haskell/Formatter/Toolkit/FileTree.hs:       OK (0.01s)
    testsuite/src/Language/Haskell/Formatter/Toolkit/TestTool.hs:       OK (0.04s)
    testsuite/src/Main.hs:                                              OK (0.03s)
  Documentation (doctest)
    src/executable/Main.hs:                                             ### Failure in src/library/Language/Haskell/Formatter/Internal/Newline.hs:35: expression `last (splitSeparatedLines $ s ++ "\LF") == ""'

<interactive>:47:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:47:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/Splitter.hs:50: expression `odd . length $ separate ["apple", "pine"] l'

<interactive>:76:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:76:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:14: expression `maybeLast [] == Nothing'

<interactive>:105:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:105:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:15: expression `maybeLast (l ++ [e]) == Just e'

<interactive>:122:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:122:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:47: expression `takeEvery 1 l == l'

<interactive>:157:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:157:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:67: expression `p <= 0 || concatenateShiftedRuns p 0 l == concatenateRuns p l'

<interactive>:186:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:186:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/StreamName.hs:17: expression `show (createStreamName s) == s'

<interactive>:207:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:207:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
Examples: 18  Tried: 18  Errors: 0  Failures: 7
FAIL
      Exception: ExitFailure 1
    testsuite/src/Main.hs:                                              ### Failure in src/library/Language/Haskell/Formatter/Internal/Newline.hs:35: expression `last (splitSeparatedLines $ s ++ "\LF") == ""'

<interactive>:47:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:47:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/Splitter.hs:50: expression `odd . length $ separate ["apple", "pine"] l'

<interactive>:76:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:76:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:14: expression `maybeLast [] == Nothing'

<interactive>:105:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:105:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:15: expression `maybeLast (l ++ [e]) == Just e'

<interactive>:122:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:122:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:47: expression `takeEvery 1 l == l'

<interactive>:157:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:157:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/ListTool.hs:67: expression `p <= 0 || concatenateShiftedRuns p 0 l == concatenateRuns p l'

<interactive>:186:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:186:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
### Failure in src/library/Language/Haskell/Formatter/Toolkit/StreamName.hs:17: expression `show (createStreamName s) == s'

<interactive>:207:3:
    Not in scope: ‘polyQuickCheck’
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:207:3:
    GHC stage restriction:
      ‘polyQuickCheck’ is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
Examples: 18  Tried: 18  Errors: 0  Failures: 7
FAIL
      Exception: ExitFailure 1
  Formatting files
    source
      comments
        depends_on_displacement
          multiple_annotations
            Formatting once:                                            OK
            Idempotence:                                                OK
          single_annotation
            line_pair
              after_after
                Formatting once:                                        OK
                Idempotence:                                            OK
              after_before
                Formatting once:                                        OK
                Idempotence:                                            OK
              after_none
                Formatting once:                                        OK
                Idempotence:                                            OK
              before_after
                Formatting once:                                        OK
                Idempotence:                                            OK
              before_before
                Formatting once:                                        OK
                Idempotence:                                            OK
              before_none
                Formatting once:                                        OK
                Idempotence:                                            OK
              none_after
                Formatting once:                                        OK
                Idempotence:                                            OK
              none_before
                Formatting once:                                        OK
                Idempotence:                                            OK
              none_none
                Formatting once:                                        OK
                Idempotence:                                            OK
            single_line
              after
                Formatting once:                                        OK
                Idempotence:                                            OK
              before
                Formatting once:                                        OK
                Idempotence:                                            OK
              none
                Formatting once:                                        OK
                Idempotence:                                            OK
        empty_lines
          at_bounds_of_file
            end
              1
                Formatting once:                                        OK
                Idempotence:                                            OK
              2
                Formatting once:                                        OK
                Idempotence:                                            OK
            start
              1
                Formatting once:                                        OK
                Idempotence:                                            OK
              2
                Formatting once:                                        OK
                Idempotence:                                            OK
          between_comments_of_different_declarations
            1
              Formatting once:                                          OK
              Idempotence:                                              OK
            2
              Formatting once:                                          OK
              Idempotence:                                              OK
          between_comments_of_same_declaration
            1
              Formatting once:                                          OK
              Idempotence:                                              OK
            2
              Formatting once:                                          OK
              Idempotence:                                              OK
            3
              Formatting once:                                          OK
              Idempotence:                                              OK
          between_declaration_and_comment
            after
              1
                Formatting once:                                        OK
                Idempotence:                                            OK
              2
                Formatting once:                                        OK
                Idempotence:                                            OK
            before
              1
                Formatting once:                                        OK
                Idempotence:                                            OK
              2
                Formatting once:                                        OK
                Idempotence:                                            OK
          between_top_level_functions
            with_type_signature
              0
                Formatting once:                                        OK
                Idempotence:                                            OK
              1
                Formatting once:                                        OK
                Idempotence:                                            OK
              2
                Formatting once:                                        OK
                Idempotence:                                            OK
            without_type_signature
              0
                Formatting once:                                        OK
                Idempotence:                                            OK
              1
                Formatting once:                                        OK
                Idempotence:                                            OK
              2
                Formatting once:                                        OK
                Idempotence:                                            OK
        indentation
          inherits_indentation_of_merged_line
            actual_code_between_start_and_commented
              Formatting once:                                          OK
              Idempotence:                                              OK
            basic
              Formatting once:                                          OK
              Idempotence:                                              OK
            indented_start
              Formatting once:                                          OK
              Idempotence:                                              OK
          keeps_indentation_with_separate_line
            Formatting once:                                            OK
            Idempotence:                                                OK
        keeps_comments_at_bounds_of_file
          end
            Formatting once:                                            OK
            Idempotence:                                                OK
          start
            Formatting once:                                            OK
            Idempotence:                                                OK
        treats_nested_comments
          Formatting once:                                              OK
          Idempotence:                                                  OK
      handles_optional_parentheses
        class_constraints
          with
            Formatting once:                                            OK
            Idempotence:                                                OK
          without
            Formatting once:                                            OK
            Idempotence:                                                OK
        class_inheritance
          with
            Formatting once:                                            OK
            Idempotence:                                                OK
          without
            Formatting once:                                            OK
            Idempotence:                                                OK
        instances
          with
            Formatting once:                                            OK
            Idempotence:                                                OK
          without
            Formatting once:                                            OK
            Idempotence:                                                OK
      literals
        does_not_escape_characters
          Formatting once:                                              OK
          Idempotence:                                                  OK
      orders_parts
        import_declarations
          Formatting once:                                              OK
          Idempotence:                                                  OK
        import_declarations_and_entities
          Formatting once:                                              OK
          Idempotence:                                                  OK
        import_entities_before_declarations
          Formatting once:                                              OK
          Idempotence:                                                  OK
        nested_import_entities
          Formatting once:                                              OK
          Idempotence:                                                  OK
        nested_import_entities_before_root_entities
          Formatting once:                                              OK
          Idempotence:                                                  OK
        root_import_entities
          Formatting once:                                              OK
          Idempotence:                                                  OK
      terminates_file_with_newline
        Formatting once:                                                OK
        Idempotence:                                                    OK
  Default style file
    Uses defaults:                                                      OK
    Is contained in readme:                                             OK

2 out of 145 tests failed (6.97s)
Test suite test: FAIL
Test suite logged to: dist/test/haskell-formatter-1.0.0-test.log
0 of 1 test suites (0 of 1 test cases) passed.

**Comment by evolutics** [comment]
Thanks for the error report. It looks like it is time to relax the version bounds on `base`. Since the `base` version can [apparently](http://stackoverflow.com/questions/21962576/cabal-sandboxes-to-test-a-package-on-hackage-requiring-a-version-of-base-i-dont) not be changed in Cabal sandboxes, I need to find another way to test different versions of `base`.

The tests that fail then are the ones using `doctest`. I will try to reproduce that once I managed to update Cabal here.

**Comment by evolutics** [comment]
For my system, it works.

Which restrictions did you remove? Is it only the upper version bound on `base` (< 4.8), or other things as well? Also, what is your version of `doctest`? Thanks.

**Comment by theNerd247** [comment]
I removed the upper bounds `base < 4.8` and it built fine. Honesty I would switch to stack. It lets you manage builds much easier and it's rather simple to port a cabal project over to it. 

If you switch to stack you can use travis-cl to configure mutliple test builds with different versions of base. [See here][1]. That's what I've been doing for my haskell projects.

[1]: http://docs.haskellstack.org/en/stable/travis_ci/

**Comment by evolutics** [comment]
Hey, that looks cool! ^^ I have not heard about Stack until now – definitely very interesting. It might take a while until I make the step. Cheers.
